language: perl
perl:
    - "5.22"
    - "5.18"
    - "5.16"
env:
    - TEST_ONLINE=1 TEST_INSTALL=1 TEST_MULTILIB=0
    - TEST_ONLINE=1 TEST_INSTALL=1 TEST_MULTILIB=1
    - TEST_ONLINE=1 TEST_INSTALL=1 TEST_MULTILIB=2
    - TEST_ONLINE=1 TEST_INSTALL=0
    - TEST_ONLINE=0 TEST_INSTALL=1 TEST_MULTILIB=0
    - TEST_ONLINE=0 TEST_INSTALL=1 TEST_MULTILIB=1
    - TEST_ONLINE=0 TEST_INSTALL=1 TEST_MULTILIB=2
    - TEST_ONLINE=0 TEST_INSTALL=0
sudo: required
install:
    - sudo bash t/travis-deps/install.sh
    - cpanm Text::Diff Capture::Tiny Test::Output
script: bash -c 'PROVE=`which prove`; sudo $PROVE -v t/*.t'
notifications:
    irc:
        channels:
            - "chat.freenode.net#sbotools"
        on_success: change
        on_failure: change
