#!/usr/bin/env perl
#
# vim: set ts=4:noet
#
# sboinstall
# script to install (a) SlackBuild(s) by name
#
# authors: Jacob Pipkin <j@dawnrazor.net>
#		   Luke Williams <xocel@iquidus.org>
# license: WTFPL <http://sam.zoy.org/wtfpl/COPYING>

use 5.16.0;
use strict;
use warnings FATAL => 'all';
use SBO::Lib;
use Getopt::Long qw(:config bundling);
use File::Basename;

my $self = basename($0);
exit 1 unless exists $ARGV[0];

my (%warnings, $build_queue, %locations);

for my $sbo (@ARGV) {
    my $queue = get_build_queue([$sbo], \%warnings);
    $build_queue = merge_queues($build_queue, $queue);
}

# populate %locations and sanity check
%locations = get_sbo_location($build_queue);
for my $sbo (@$build_queue) {
  print $sbo . "\n";
}
